name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: tests/quake/deps
          key: ${{ runner.os }}-${{ hashFiles('tests/quake/__init__.py') }}
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m tests.quake setup
      - name: Install package
        run: python -m pip install .
      - name: Run tests
        run: python -m unittest discover -v
